inherit_from: "configs/mydata/base_config.yaml"

Dataset:
  dataset_path: "datasets/mydata/under"
  Calibration:
    fx: 607.514
    fy: 607.27
    cx: 640.54
    cy: 365.744
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    width: 1280
    height: 960
    depth_scale: 5000.0
    distorted: False
